# Generated by Django 5.0 on 2024-02-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0002_agentbigtimebundleprice_bigtimebundleprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='message',
        ),
        migrations.AddField(
            model_name='payment',
            name='channel',
            field=models.CharField(blank=True, choices=[('mtn', 'mtn'), ('ishare', 'ishare'), ('bigtime', 'bigtime'), ('afa', 'afa'), ('topup', 'topup')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_status',
            field=models.CharField(blank=True, default='Unfinished', max_length=256, null=True),
        ),
    ]
