# Generated by Django 4.2.4 on 2024-08-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0011_admininfo_paystack_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('lime', 'Lime'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('gold', 'Gold'), ('silver', 'Silver'), ('maroon', 'Maroon'), ('olive', 'Olive'), ('teal', 'Teal'), ('navy', 'Navy'), ('beige', 'Beige'), ('coral', 'Coral'), ('salmon', 'Salmon'), ('khaki', 'Khaki'), ('plum', 'Plum'), ('orchid', 'Orchid'), ('turquoise', 'Turquoise'), ('lavender', 'Lavender'), ('Bronze', 'Bronze'), ('Blue-Black', 'Blue-Black'), ('Rose', 'Rose')], max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Out for Delivery', 'Out for Delivery'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=50),
        ),
    ]
