# Generated by Django 4.2.4 on 2025-01-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0013_mtntransaction_amount_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigtimetransaction',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teleceltransaction',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
