# Generated by Django 4.2.4 on 2025-01-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0014_bigtimetransaction_amount_teleceltransaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='ishare_source',
            field=models.CharField(default='Geosams', max_length=300),
        ),
        migrations.AlterField(
            model_name='bigtimetransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='isharebundletransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='mtntransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='teleceltransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
