# Generated by Django 4.2.4 on 2025-03-10 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0015_admininfo_ishare_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=150)),
                ('serial_number', models.CharField(max_length=150)),
                ('used', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('checker_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intel_app.checkertype')),
            ],
        ),
        migrations.CreateModel(
            name='ResultCheckerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_bought', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('result_checker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intel_app.resultchecker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
