# Generated by Django 4.2.4 on 2025-06-16 12:19

from django.db import migrations, models
import intel_app.custom_storages


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0017_alter_admininfo_ishare_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=intel_app.custom_storages.MediaStorage(), upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=intel_app.custom_storages.MediaStorage(), upload_to='product_images/'),
        ),
    ]
