# Generated by Django 4.2.4 on 2025-06-16 16:39

from django.db import migrations, models
import intel_app.custom_storages


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0019_currency_currencytransaction_currencyratehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='rate',
            new_name='personal_rate',
        ),
        migrations.AddField(
            model_name='currency',
            name='supplier_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currencytransaction',
            name='qr_code_for_payment',
            field=models.ImageField(blank=True, null=True, storage=intel_app.custom_storages.MediaStorage(), upload_to='payment_qr_codes/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='forex_status',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Supplier', 'Supplier')], default='Personal', max_length=250, null=True),
        ),
    ]
