# Generated by Django 4.2.4 on 2025-06-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0020_rename_rate_currency_personal_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencytransaction',
            name='recipient_full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
