# Generated by Django 4.2.4 on 2025-06-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0021_currencytransaction_recipient_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytransaction',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Refunded', 'Refunded')], default='Pending', max_length=250, null=True),
        ),
    ]
