# Generated by Django 4.2.4 on 2025-06-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0022_alter_currencytransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='forex_minimum_amount',
            field=models.FloatField(default=200),
        ),
    ]
