# Generated by Django 4.2.4 on 2025-06-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0023_admininfo_forex_minimum_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='send_sms_for_forex',
            field=models.BooleanField(default=False),
        ),
    ]
